/* MY EDITOR V127 — IME-safe editing + reliable backward reflow */
(() => {
  function installV127(){
    const ed=document.getElementById('editor');
    if(!ed || typeof current!=='function') return;
    document.documentElement.dataset.editingEngine='127';

    let composing=false, reflowTimer=null;

    function runReflow({keepCaret=true}={}){
      if(composing) return;
      clearTimeout(reflowTimer);
      reflowTimer=setTimeout(()=>{
        try{
          const s=current();
          if(!s?.pages?.length)return;
          /* Pages created by automatic overflow must always belong to the same flow. */
          s.pages.forEach((p,i)=>{
            if(i>0 && p.autoGenerated===true){
              p.userManualPage=false;
              p.manualBreakBefore=false;
            }
          });
          if(typeof window.reflowDocumentV121==='function'){
            window.reflowDocumentV121({keepCaret,goFirst:false});
          }else if(typeof window.reflowAllAutoPagesFromCurrentSlot==='function'){
            window.reflowAllAutoPagesFromCurrentSlot();
          }
        }catch(e){console.error('V127 reflow failed',e)}
      },110);
    }

    /* Never rebuild the editor while Korean/Japanese/Chinese IME composition is active. */
    ed.addEventListener('compositionstart',()=>{
      composing=true;
      try{window.isPaginating=true}catch{}
      clearTimeout(reflowTimer);
    },true);

    ed.addEventListener('compositionend',()=>{
      composing=false;
      try{window.isPaginating=false}catch{}
      /* Let the browser commit the final composed text before pagination. */
      setTimeout(()=>runReflow({keepCaret:true}),160);
    },true);

    /* Input events generated during composition must not cause secondary page work. */
    ed.addEventListener('beforeinput',e=>{
      if(e.isComposing || String(e.inputType||'').includes('Composition')){
        composing=true;
        try{window.isPaginating=true}catch{}
      }
    },true);

    ed.addEventListener('input',e=>{
      if(e.isComposing || composing) return;
      const type=String(e.inputType||'');
      /* Deletion is the important backward-flow case. Ordinary insertions are left to
         the canonical page engine, avoiding duplicate renders while typing. */
      if(type.startsWith('delete')) runReflow({keepCaret:true});
    },false);

    ed.addEventListener('keyup',e=>{
      if(!composing && (e.key==='Backspace'||e.key==='Delete')) runReflow({keepCaret:true});
    },false);

    /* After paste/slot load/font settle, normalize all automatic pages once. */
    setTimeout(()=>runReflow({keepCaret:false}),700);
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(installV127,0),{once:true});
  else setTimeout(installV127,0);
})();