/* MY EDITOR V106/V114 — authoritative continuous page flow + caret preservation */
(() => {
  function installContinuousPagination(){
    const $id=id=>document.getElementById(id);
    const ed=$id("editor");
    if(!ed || typeof current!=="function" || typeof extractOverflowChunks!=="function")return;

    let running=false;
    let timer=null;
    let pendingCaret=null;

    try{ if(typeof handleEditorInput==="function")ed.removeEventListener("input",handleEditorInput); }catch{}

    /* Auto-generated pages remain continuation pages even though v110 mirrors the master
       title/subtitle onto them. The previous title/subtitle check broke chain detection. */
    function isContinuation(page){ return !!page?.autoGenerated; }

    function plainLength(html){
      if(typeof strip==="function")return strip(html||"").length;
      const box=document.createElement("div");box.innerHTML=html||"";return (box.textContent||"").length;
    }

    function caretOffsetInEditor(){
      const sel=getSelection();
      if(!sel?.rangeCount)return null;
      const r=sel.getRangeAt(0);
      if(!ed.contains(r.startContainer))return null;
      const pre=r.cloneRange();pre.selectNodeContents(ed);pre.setEnd(r.startContainer,r.startOffset);
      return pre.toString().length;
    }

    function restoreCaretInEditor(offset){
      offset=Math.max(0,Number(offset)||0);
      const walker=document.createTreeWalker(ed,NodeFilter.SHOW_TEXT);
      let total=0,node,last=null;
      while((node=walker.nextNode())){
        last=node;const len=node.nodeValue.length;
        if(offset<=total+len){
          const range=document.createRange();range.setStart(node,Math.max(0,offset-total));range.collapse(true);
          const sel=getSelection();sel.removeAllRanges();sel.addRange(range);
          try{savedRange=range.cloneRange()}catch{};ed.focus({preventScroll:true});return true;
        }
        total+=len;
      }
      const range=document.createRange();range.selectNodeContents(ed);range.collapse(false);
      const sel=getSelection();sel.removeAllRanges();sel.addRange(range);
      try{savedRange=range.cloneRange()}catch{};ed.focus({preventScroll:true});return true;
    }

    function saveLivePage(){
      const s=current(),p=s.pages[s.currentPageIndex];if(!p)return;
      const title=$id("titleInput"),subtitle=$id("subtitleInput");
      if(title)p.title=title.value;if(subtitle)p.subtitle=subtitle.value;
      p.content=ed.innerHTML;s.updatedAt=new Date().toISOString();
    }

    function rootIndexFor(slot,index){
      let i=Math.max(0,Math.min(index,slot.pages.length-1));
      while(i>0 && isContinuation(slot.pages[i]))i--;
      return i;
    }
    function chainEndFor(slot,root){let i=root+1;while(i<slot.pages.length&&isContinuation(slot.pages[i]))i++;return i;}

    function logicalCaretForCurrentChain(){
      const slot=current(),currentIndex=slot.currentPageIndex||0,root=rootIndexFor(slot,currentIndex),local=caretOffsetInEditor();
      if(local==null)return null;
      let absolute=local;for(let i=root;i<currentIndex;i++)absolute+=plainLength(slot.pages[i].content||"");
      return {rootId:slot.pages[root]?.id,absolute};
    }

    function loadPageForMeasure(slot,index){
      const p=slot.pages[index];slot.currentPageIndex=index;
      $id("titleInput").value=p.title||"";$id("subtitleInput").value=p.subtitle||"";ed.innerHTML=p.content||"";
      if(typeof applyTypography==="function")applyTypography();
      if(typeof applyDocumentLayout==="function")applyDocumentLayout();
      if(typeof normalizeEditorTopLevel==="function")normalizeEditorTopLevel();
      void ed.offsetHeight;
    }

    function cleanEmptyTail(slot,root){
      const end=chainEndFor(slot,root);
      for(let i=end-1;i>root;i--){const p=slot.pages[i];if(isContinuation(p)&&!plainLength(p.content||""))slot.pages.splice(i,1);else break;}
    }

    function targetForLogicalCaret(slot,root,marker){
      if(!marker)return null;
      const end=chainEndFor(slot,root);let remaining=Math.max(0,marker.absolute);
      for(let i=root;i<end;i++){
        const len=plainLength(slot.pages[i].content||"");
        if(remaining<=len||i===end-1)return {index:i,offset:Math.min(remaining,len)};
        remaining-=len;
      }
      return {index:root,offset:0};
    }

    function finishOnPage(slot,index,caretOffset=null){
      slot.currentPageIndex=Math.max(0,Math.min(index,slot.pages.length-1));
      try{persist?.()}catch{};try{renderAll?.()}catch{}
      if(caretOffset!=null)requestAnimationFrame(()=>requestAnimationFrame(()=>restoreCaretInEditor(caretOffset)));
    }

    function reflowContinuousChain({caretMarker=null,announce=true}={}){
      if(running||isPaginating)return false;
      const slot=current();if(!slot?.pages?.length)return false;
      saveLivePage();
      const originalIndex=Math.max(0,Math.min(slot.currentPageIndex||0,slot.pages.length-1));
      const root=rootIndexFor(slot,originalIndex),oldEnd=chainEndFor(slot,root),oldCount=oldEnd-root;
      let combined="";for(let i=root;i<oldEnd;i++)combined+=slot.pages[i].content||"";
      const rootPage=slot.pages[root];slot.pages.splice(root+1,oldEnd-root-1);rootPage.content=combined;

      running=true;isPaginating=true;let created=0;
      try{
        let index=root,carry=combined;
        while(true){
          const page=slot.pages[index];page.content=carry;loadPageForMeasure(slot,index);
          const moved=extractOverflowChunks();page.content=ed.innerHTML;
          if(!moved.length)break;
          carry=moved.join("");
          const next=newPage(index+2,true);
          /* mirror heading for display but autoGenerated remains the flow identity */
          next.title=rootPage.title||"";next.subtitle=rootPage.subtitle||"";next.content=carry;next.pageTypography={};next.pageDecorations=[];
          slot.pages.splice(index+1,0,next);created++;index++;
          if(created>200)break;
        }
        cleanEmptyTail(slot,root);try{renumberPages?.()}catch{}
        const newCount=chainEndFor(slot,root)-root,target=targetForLogicalCaret(slot,root,caretMarker);
        const restoreIndex=target?.index??Math.min(originalIndex,slot.pages.length-1);
        if(announce&&created>0&&newCount>oldCount)try{showPageAddedNotice?.()}catch{}
        isPaginating=false;running=false;finishOnPage(slot,restoreIndex,target?.offset??null);return true;
      }catch(err){
        console.error("continuous pagination failed",err);isPaginating=false;running=false;finishOnPage(slot,Math.min(originalIndex,slot.pages.length-1),caretMarker?caretOffsetInEditor():null);return false;
      }
    }

    window.reflowAllAutoPagesFromCurrentSlot=reflowAllAutoPagesFromCurrentSlot=function(){
      if(running||isPaginating)return;
      const slot=current();if(!slot?.pages?.length)return;
      saveLivePage();const originalIndex=slot.currentPageIndex||0;
      let root=0;
      while(root<slot.pages.length){
        slot.currentPageIndex=root;loadPageForMeasure(slot,root);
        reflowContinuousChain({caretMarker:null,announce:false});
        root=chainEndFor(slot,root);
      }
      finishOnPage(slot,Math.min(originalIndex,slot.pages.length-1),null);
    };

    function schedule(marker=null,delay=70){
      clearTimeout(timer);pendingCaret=marker||pendingCaret;
      timer=setTimeout(()=>requestAnimationFrame(()=>{const m=pendingCaret;pendingCaret=null;reflowContinuousChain({caretMarker:m,announce:true});}),delay);
    }

    ed.addEventListener("input",()=>{
      saveLivePage();const marker=logicalCaretForCurrentChain();pendingCaret=marker;
      try{persist?.();updateCount?.();renderSlots?.()}catch{};schedule(marker,55);
    });

    $id("titleInput")?.addEventListener("input",()=>{saveLivePage();try{persist?.()}catch{};schedule(null,120)});
    $id("subtitleInput")?.addEventListener("input",()=>{saveLivePage();try{persist?.()}catch{};schedule(null,120)});
    document.addEventListener("change",e=>{if(e.target?.closest?.(".panel-body,.right-panel"))schedule(null,170)});
    document.addEventListener("input",e=>{if(e.target===ed||e.target===$id("titleInput")||e.target===$id("subtitleInput"))return;if(e.target?.matches?.('input[type="range"],input[type="number"]'))schedule(null,170)});
    setTimeout(()=>{try{reflowAllAutoPagesFromCurrentSlot()}catch(e){console.error(e)}},650);
  }
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>setTimeout(installContinuousPagination,0),{once:true});else setTimeout(installContinuousPagination,0);
})();
