/* MY EDITOR developer notice config */
window.MY_EDITOR_NOTICE={enabled:false,current:{id:"notice-2026-08-18-01",type:"info",title:"MY EDITOR 공지",message:"공지 내용을 여기에 입력하세요.",date:"2026-08-18"},history:[],developerKey:"change-this-developer-key"};
window.MY_EDITOR_AUTO_UPDATE_NOTICE={enabled:true,version:"125",title:"업데이트 안내",message:"본문의 의도치 않은 배경색을 제거하고 실제 형광펜(span.text-highlight)만 유지하도록 수정했습니다. 미리보기/저장은 별도 레이아웃 재계산 대신 실제 작업 paper를 그대로 복제하도록 변경했습니다. 제목·본문 간격은 음수 범위까지 조절할 수 있게 확장했습니다.\n새로고침 후 다시 사용해주세요."};
if(document.readyState==="loading"){
 document.write('<link rel="stylesheet" href="hotfix-v104.css?v=104">');document.write('<link rel="stylesheet" href="hotfix-v105.css?v=105">');document.write('<link rel="stylesheet" href="hotfix-v109.css?v=117">');document.write('<link rel="stylesheet" href="hotfix-v110.css?v=120">');document.write('<link rel="stylesheet" href="hotfix-v112.css?v=117">');document.write('<link rel="stylesheet" href="hotfix-v113.css?v=117">');document.write('<link rel="stylesheet" href="hotfix-v121.css?v=123">');document.write('<link rel="stylesheet" href="hotfix-v124.css?v=124">');
 document.write('<script src="hotfix-v104.js?v=104"></script>');document.write('<script src="hotfix-v105.js?v=105"></script>');document.write('<script src="hotfix-v106.js?v=120"></script>');document.write('<script src="hotfix-v107.js?v=107"></script>');document.write('<script src="hotfix-v108.js?v=114"></script>');document.write('<script src="hotfix-v109.js?v=117"></script>');document.write('<script src="hotfix-v110.js?v=114"></script>');document.write('<script src="hotfix-v112.js?v=117"></script>');document.write('<script src="hotfix-v113.js?v=117"></script>');document.write('<script src="hotfix-v121.js?v=123"></script>');document.write('<script src="hotfix-v124.js?v=124"></script>');document.write('<script src="hotfix-v125.js?v=125"></script>');
}else{
 for(const href of ["hotfix-v104.css?v=104","hotfix-v105.css?v=105","hotfix-v109.css?v=117","hotfix-v110.css?v=120","hotfix-v112.css?v=117","hotfix-v113.css?v=117","hotfix-v121.css?v=123","hotfix-v124.css?v=124"]){const link=document.createElement("link");link.rel="stylesheet";link.href=href;document.head.appendChild(link)}
 for(const src of ["hotfix-v104.js?v=104","hotfix-v105.js?v=105","hotfix-v106.js?v=120","hotfix-v107.js?v=107","hotfix-v108.js?v=114","hotfix-v109.js?v=117","hotfix-v110.js?v=114","hotfix-v112.js?v=117","hotfix-v113.js?v=117","hotfix-v121.js?v=123","hotfix-v124.js?v=124","hotfix-v125.js?v=125"]){const script=document.createElement("script");script.src=src;script.async=false;document.body.appendChild(script)}
}
