/* MY EDITOR developer notice config */
window.MY_EDITOR_NOTICE={enabled:false,current:{id:"notice-2026-08-18-01",type:"info",title:"MY EDITOR 공지",message:"공지 내용을 여기에 입력하세요.",date:"2026-08-18"},history:[],developerKey:"change-this-developer-key"};
window.MY_EDITOR_AUTO_UPDATE_NOTICE={enabled:true,version:"124",title:"업데이트 안내",message:"1단 문서에서도 CSS 다단 기능이 켜져 있어 넘친 본문이 오른쪽 추가 컬럼으로 빠지던 문제를 수정했습니다. 1단에서는 다단 레이아웃을 완전히 끄고 정상적인 페이지 높이 기준으로 재분할합니다. 새 페이지/페이지 삭제 버튼 UI도 같은 크기와 간격으로 정리했습니다.\n새로고침 후 다시 사용해주세요."};
if(document.readyState==="loading"){
 document.write('<link rel="stylesheet" href="hotfix-v104.css?v=104">');document.write('<link rel="stylesheet" href="hotfix-v105.css?v=105">');document.write('<link rel="stylesheet" href="hotfix-v109.css?v=117">');document.write('<link rel="stylesheet" href="hotfix-v110.css?v=120">');document.write('<link rel="stylesheet" href="hotfix-v112.css?v=117">');document.write('<link rel="stylesheet" href="hotfix-v113.css?v=117">');document.write('<link rel="stylesheet" href="hotfix-v121.css?v=123">');document.write('<link rel="stylesheet" href="hotfix-v124.css?v=124">');
 document.write('<script src="hotfix-v104.js?v=104"></script>');document.write('<script src="hotfix-v105.js?v=105"></script>');document.write('<script src="hotfix-v106.js?v=120"></script>');document.write('<script src="hotfix-v107.js?v=107"></script>');document.write('<script src="hotfix-v108.js?v=114"></script>');document.write('<script src="hotfix-v109.js?v=117"></script>');document.write('<script src="hotfix-v110.js?v=114"></script>');document.write('<script src="hotfix-v112.js?v=117"></script>');document.write('<script src="hotfix-v113.js?v=117"></script>');document.write('<script src="hotfix-v121.js?v=123"></script>');document.write('<script src="hotfix-v124.js?v=124"></script>');
}else{
 for(const href of ["hotfix-v104.css?v=104","hotfix-v105.css?v=105","hotfix-v109.css?v=117","hotfix-v110.css?v=120","hotfix-v112.css?v=117","hotfix-v113.css?v=117","hotfix-v121.css?v=123","hotfix-v124.css?v=124"]){const link=document.createElement("link");link.rel="stylesheet";link.href=href;document.head.appendChild(link)}
 for(const src of ["hotfix-v104.js?v=104","hotfix-v105.js?v=105","hotfix-v106.js?v=120","hotfix-v107.js?v=107","hotfix-v108.js?v=114","hotfix-v109.js?v=117","hotfix-v110.js?v=114","hotfix-v112.js?v=117","hotfix-v113.js?v=117","hotfix-v121.js?v=123","hotfix-v124.js?v=124"]){const script=document.createElement("script");script.src=src;script.async=false;document.body.appendChild(script)}
}
