const $=id=>document.getElementById(id);
const KEY="my-writing-editor-v2";
const DB="my-writing-editor-assets-v10", DBV=2, FONT_STORE="fonts", BG_STORE="backgrounds", SLOT_IMG_STORE="slotImages";

let savedRange=null, slotMenuTarget=null, activeBgUrl=null, customFontUrls=new Map(), slotImageUrls=new Map(), isPaginating=false, draggedSlotId=null;
let state=loadState();
let currentSlotId=state.currentSlotId;

const DISTRIBUTION_TYPOGRAPHY={
  fontFamily:"Pretendard",fontSizePt:12,textColor:"#3f3d3b",highlightColor:"#fff2a8",
  letterSpacing:0,lineHeight:1.25,paragraphSpacing:0,widthScale:100
};
const DISTRIBUTION_BACKGROUND={
  mode:"solid",solid:"#ffffff",grad1:"#ffffff",grad2:"#e8e2da",angle:135,
  imageId:null,imageAverageColor:null,size:"cover",brightness:100,
  effect:"none",effectOpacity:18,effectColor:"#8f887f",effectAutoColor:true,
  decorations:[],dividerSize:16,dividerMargin:18,
  paperBorderStyle:"none",paperBorderColor:"#d8d2c8",paperBorderWidth:1,
  paperInnerInset:0,paperBorderOpacity:100,paperBorderAutoColor:true,
  paperFrameStyle:"none",paperFrameColor:"#bdb5a8",paperFrameOpacity:100,
  paperFrameAutoColor:true,paperShadow:16
};
function defaultTypography(){return structuredClone(DISTRIBUTION_TYPOGRAPHY)}
function defaultBackground(){return structuredClone(DISTRIBUTION_BACKGROUND)}
function newPage(n,autoGenerated=false){return{id:crypto.randomUUID?.()||String(Date.now()+Math.random()),title:"",subtitle:"",content:"",pagePrefix:"—",pageNumber:String(n).padStart(2,"0"),pageSuffix:"—",pageTypography:{},pageDecorations:[],autoGenerated}}
function newSlot(i){return{id:crypto.randomUUID?.()||String(Date.now()+Math.random()),name:`새 문서 ${String(i).padStart(2,"0")}`,pages:[newPage(1)],currentPageIndex:0,typography:defaultTypography(),background:defaultBackground(),updatedAt:null}}

function loadState(){
  try{
    const raw=localStorage.getItem(KEY);
    if(raw){
      const old=JSON.parse(raw);
      if(old.slots?.length){
        const slots=old.slots.map((s,i)=>{
          const d=newSlot(i+1);
          const migratedPages = Array.isArray(s.pages) && s.pages.length
            ? s.pages.map((p,pi)=>({...newPage(pi+1,false),...p,pageTypography:{...(p.pageTypography||{})},pageDecorations:[...(p.pageDecorations||[])],autoGenerated:!!p.autoGenerated}))
            : [{...newPage(1),title:s.title||"",subtitle:s.subtitle||"",content:s.content||"",pagePrefix:s.pagePrefix??"—",pageNumber:s.pageNumber??"01",pageSuffix:s.pageSuffix??"—"}];
          return {...d,...s,pages:migratedPages,currentPageIndex:Math.min(s.currentPageIndex||0,migratedPages.length-1),typography:{...d.typography,...(s.typography||{})},background:{...d.background,...(s.background||{}),...(old.appearance?{
            mode:old.appearance.mode||"solid",solid:old.appearance.solid||"#fff",grad1:old.appearance.gradient1||"#fff",grad2:old.appearance.gradient2||"#eee",
            angle:old.appearance.gradientAngle||135,imageId:old.appearance.backgroundAssetId||null,size:old.appearance.backgroundSize||"cover",brightness:old.appearance.backgroundBrightness||100
          }:{})}}
        });
        return{slots,currentSlotId:old.currentSlotId||slots[0].id};
      }
    }
  }catch(e){console.warn(e)}
  const slots=Array.from({length:4},(_,i)=>newSlot(i+1));
  return{slots,currentSlotId:slots[0].id}
}
function persist(){localStorage.setItem(KEY,JSON.stringify(state))}
function current(){return state.slots.find(s=>s.id===currentSlotId)||state.slots[0]}
function currentPage(){const s=current();return s.pages[s.currentPageIndex]||s.pages[0]}

function strip(html){const d=document.createElement("div");d.innerHTML=html||"";return d.textContent||""}

function bindIf(id,event,handler){
  const el=$(id);
  if(el)el[event]=handler;
}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function safe(v){return String(v||"document").replace(/[\\/:*?"<>|]/g,"_")}

function renderSlots(){
  const list=$("slotList");
  list.innerHTML="";
  state.slots.forEach((s,i)=>{
    const card=document.createElement("div");
    card.className="slot-card"+(s.id===currentSlotId?" active":"");
    card.draggable=true;
    card.dataset.slotId=s.id;
    const p=s.pages?.[s.currentPageIndex||0]||s.pages?.[0]||{};
    card.innerHTML=`<button class="slot-main">
      <div class="slot-badge">${String(i+1).padStart(2,"0")}</div>
      <div class="slot-no">SLOT ${String(i+1).padStart(2,"0")} · ${s.pages?.length||1}P</div>
      <div class="slot-name">${esc(s.name)}</div>
      <div class="slot-preview">${esc(strip(p.content)||p.subtitle||"비어 있음")}</div>
    </button><button class="slot-more" aria-label="슬롯 편집">⋯</button>`;

    card.querySelector(".slot-main").onclick=()=>{
      saveCurrent(false);currentSlotId=s.id;state.currentSlotId=s.id;persist();renderAll();
    };
    card.querySelector(".slot-more").onclick=e=>openSlotMenu(e,s.id);

    card.addEventListener("dragstart",e=>{
      draggedSlotId=s.id;card.classList.add("dragging");
      e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",s.id);
    });
    card.addEventListener("dragend",()=>{
      draggedSlotId=null;
      document.querySelectorAll(".slot-card").forEach(c=>c.classList.remove("dragging","drag-over"));
    });
    card.addEventListener("dragover",e=>{
      e.preventDefault();
      if(draggedSlotId&&draggedSlotId!==s.id)card.classList.add("drag-over");
    });
    card.addEventListener("dragleave",()=>card.classList.remove("drag-over"));
    card.addEventListener("drop",e=>{
      e.preventDefault();card.classList.remove("drag-over");
      reorderSlots(e.dataTransfer.getData("text/plain")||draggedSlotId,s.id);
    });

    list.appendChild(card);
    loadSlotThumbnail(s.id,card);
  });
}
function reorderSlots(fromId,toId){
  if(!fromId||!toId||fromId===toId)return;
  const from=state.slots.findIndex(s=>s.id===fromId),to=state.slots.findIndex(s=>s.id===toId);
  if(from<0||to<0)return;
  const [moved]=state.slots.splice(from,1);state.slots.splice(to,0,moved);
  persist();renderSlots();
}
async function loadSlotThumbnail(slotId,card){
  try{
    const asset=await getAsset(SLOT_IMG_STORE,slotId);if(!asset?.file)return;
    if(slotImageUrls.has(slotId))URL.revokeObjectURL(slotImageUrls.get(slotId));
    const url=URL.createObjectURL(asset.file);slotImageUrls.set(slotId,url);
    const badge=card.querySelector(".slot-badge");if(!badge)return;
    const img=document.createElement("img");img.className="slot-image-thumb";img.src=url;img.alt="";
    badge.replaceWith(img);
  }catch{}
}

function renderAll(){
  const s=current(); if(!s)return;
  const p=currentPage();
  const idx=state.slots.findIndex(x=>x.id===s.id)+1;
  $("slotLabel").textContent=`SLOT ${String(idx).padStart(2,"0")}`;
  $("pageNavLabel").textContent=`PAGE ${String(s.currentPageIndex+1).padStart(2,"0")} / ${String(s.pages.length).padStart(2,"0")}`;
  $("titleInput").value=p.title||"";
  if(p.title?.trim())s.name=p.title.trim();
  $("subtitleInput").value=p.subtitle||"";
  $("editor").innerHTML=p.content||"";
  $("pageNumberPreview").textContent=[p.pagePrefix,p.pageNumber,p.pageSuffix].filter(Boolean).join(" ");
  applyTypography();
  syncControls();
  applyBackground();
  renderSlots();
  updateCount();
}
function saveCurrent(mark=true){
  const s=current();if(!s)return;
  const p=currentPage();
  p.title=$("titleInput").value;p.subtitle=$("subtitleInput").value;p.content=$("editor").innerHTML;s.updatedAt=new Date().toISOString();
  persist();updateCount();renderSlots();
  $("lastSaved").textContent="저장 "+new Date(s.updatedAt).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"});
  if(mark){$("saveStatus").textContent="저장됨 ✓";setTimeout(()=>$("saveStatus").textContent="자동 저장됨",800)}
}
let saveTimer;
function scheduleSave(){clearTimeout(saveTimer);$("saveStatus").textContent="저장 중…";saveTimer=setTimeout(()=>saveCurrent(),300);updateCount()}
function updateCount(){const n=strip($("editor").innerHTML).replace(/\s/g,"").length;$("charCount").textContent=`${n.toLocaleString()}자`}


function addPage(){
  saveCurrent(false);
  const s=current();
  s.pages.push(newPage(s.pages.length+1,false));
  s.currentPageIndex=s.pages.length-1;
  persist();
  renderAll();
}
function goPage(delta){
  saveCurrent(false);
  const s=current();
  const next=Math.max(0,Math.min(s.pages.length-1,s.currentPageIndex+delta));
  if(next===s.currentPageIndex)return;
  s.currentPageIndex=next;
  persist();
  renderAll();
}
function deletePage(){
  const s=current();
  if(s.pages.length<=1){alert("페이지는 최소 1개가 필요합니다.");return}
  if(!confirm("현재 페이지를 삭제할까요?"))return;
  s.pages.splice(s.currentPageIndex,1);
  s.currentPageIndex=Math.max(0,Math.min(s.currentPageIndex,s.pages.length-1));
  s.pages.forEach((p,i)=>{ if(!p.pageNumber || /^\d+$/.test(String(p.pageNumber))) p.pageNumber=String(i+1).padStart(2,"0") });
  persist();
  renderAll();
}
$("addPageBtn").onclick=addPage;
$("prevPageBtn").onclick=()=>goPage(-1);
$("nextPageBtn").onclick=()=>goPage(1);
$("deletePageBtn").onclick=deletePage;

async function openSlotMenu(e,id){
  e.stopPropagation();slotMenuTarget=id;saveCurrent(false);
  const idx=state.slots.findIndex(s=>s.id===id),s=state.slots[idx];
  $("slotModalBadge").textContent=String(idx+1).padStart(2,"0");
  $("slotModalLabel").textContent=`SLOT ${String(idx+1).padStart(2,"0")}`;
  $("slotModalPages").textContent=`${s.pages?.length||1} PAGE${(s.pages?.length||1)>1?"S":""}`;
  $("slotModalName").value=s.name||"";
  const img=$("slotModalImagePreview");img.hidden=true;$("slotModalBadge").hidden=false;
  try{
    const asset=await getAsset(SLOT_IMG_STORE,id);
    if(asset?.file){
      if(slotImageUrls.has("modal"))URL.revokeObjectURL(slotImageUrls.get("modal"));
      const url=URL.createObjectURL(asset.file);slotImageUrls.set("modal",url);
      img.src=url;img.hidden=false;$("slotModalBadge").hidden=true;
    }
  }catch{}
  $("slotEditorModal").hidden=false;
}
function closeSlotEditor(){$("slotEditorModal").hidden=true}
document.querySelectorAll("[data-close-slot-editor]").forEach(x=>x.onclick=closeSlotEditor);
$("slotModalSaveBtn").onclick=()=>{
  if(slotMenuTarget!==currentSlotId){currentSlotId=slotMenuTarget;state.currentSlotId=slotMenuTarget;renderAll()}
  saveCurrent();closeSlotEditor();
};
$("slotModalDuplicateBtn").onclick=async()=>{
  const idx=state.slots.findIndex(s=>s.id===slotMenuTarget);if(idx<0)return;
  const c=structuredClone(state.slots[idx]);c.id=crypto.randomUUID?.()||String(Date.now()+Math.random());c.name+=" 복사본";
  c.pages=c.pages.map(p=>({...p,id:crypto.randomUUID?.()||String(Date.now()+Math.random())}));
  state.slots.splice(idx+1,0,c);
  try{const img=await getAsset(SLOT_IMG_STORE,slotMenuTarget);if(img?.file)await putAsset(SLOT_IMG_STORE,{id:c.id,file:img.file,name:img.name||"slot-image"})}catch{}
  currentSlotId=c.id;state.currentSlotId=c.id;persist();closeSlotEditor();renderAll();
};
$("slotModalDeleteBtn").onclick=async()=>{
  const idx=state.slots.findIndex(s=>s.id===slotMenuTarget);
  if(idx<0)return;
  if(!confirm("이 슬롯을 삭제할까요?"))return;

  const deletedId=state.slots[idx].id;
  state.slots.splice(idx,1);
  try{await delAsset(SLOT_IMG_STORE,deletedId)}catch{}

  if(!state.slots.length){
    state.slots.push(newSlot(1));
  }

  if(currentSlotId===deletedId){
    const target=Math.min(idx,state.slots.length-1);
    currentSlotId=state.slots[target].id;
    state.currentSlotId=currentSlotId;
  }

  persist();
  closeSlotEditor();
  renderAll();
};
$("slotImageInput").onchange=async e=>{
  const f=e.target.files?.[0];if(!f||!slotMenuTarget)return;
  await putAsset(SLOT_IMG_STORE,{id:slotMenuTarget,file:f,name:f.name});
  await openSlotMenu({stopPropagation(){}},slotMenuTarget);renderSlots();e.target.value="";
};
$("removeSlotImageBtn").onclick=async()=>{
  if(!slotMenuTarget)return;
  try{await delAsset(SLOT_IMG_STORE,slotMenuTarget)}catch{}
  await openSlotMenu({stopPropagation(){}},slotMenuTarget);renderSlots();
};

$("addSlotBtn").onclick=()=>{saveCurrent(false);const s=newSlot(state.slots.length+1);state.slots.push(s);currentSlotId=s.id;state.currentSlotId=s.id;persist();renderAll()};

$("titleInput").addEventListener("input",()=>{
  const s=current();
  const idx=state.slots.findIndex(x=>x.id===s.id)+1;
  const title=$("titleInput").value.trim();
  s.name=title || `새 문서 ${String(idx).padStart(2,"0")}`;
  scheduleSave();
});
$("subtitleInput").addEventListener("input",scheduleSave);
$("editor").addEventListener("beforeinput",e=>{lastEditorInputType=e.inputType||""});
$("editor").addEventListener("input",handleEditorInput);



function renumberPages(){
  current().pages.forEach((p,i)=>{if(!p.pageNumber||/^\d+$/.test(String(p.pageNumber)))p.pageNumber=String(i+1).padStart(2,"0")});
}
function editorOverflows(){const ed=$("editor");return ed.scrollHeight>ed.clientHeight+2}
function normalizeEditorTopLevel(){
  const ed=$("editor");
  [...ed.childNodes].forEach(node=>{
    if(node.nodeType===Node.TEXT_NODE&&node.nodeValue.trim()){
      const p=document.createElement("p");p.textContent=node.nodeValue;ed.replaceChild(p,node);
    }
  });
}
function nodeHTML(node){
  if(node.nodeType===Node.TEXT_NODE)return esc(node.nodeValue);
  return node.outerHTML||"";
}
function placeCaretAfterTopNode(index){
  const ed=$("editor"),node=ed.childNodes[Math.max(0,Math.min(index,ed.childNodes.length-1))];
  if(!node){ed.focus();return}
  const range=document.createRange();range.selectNodeContents(node);range.collapse(false);
  const sel=getSelection();sel.removeAllRanges();sel.addRange(range);savedRange=range.cloneRange();ed.focus();
}
let lastEditorInputType="";

function renumberPages(){
  current().pages.forEach((p,i)=>{
    if(!p.pageNumber || /^\d+$/.test(String(p.pageNumber))){
      p.pageNumber=String(i+1).padStart(2,"0");
    }
  });
}
function editorOverflows(){
  const ed=$("editor");
  return ed.scrollHeight > ed.clientHeight + 2;
}
function normalizeEditorTopLevel(){
  const ed=$("editor");
  [...ed.childNodes].forEach(node=>{
    if(node.nodeType===Node.TEXT_NODE && node.nodeValue.trim()){
      const p=document.createElement("p");
      p.textContent=node.nodeValue;
      ed.replaceChild(p,node);
    }
  });
}
function nodeHTML(node){
  if(node.nodeType===Node.TEXT_NODE)return esc(node.nodeValue);
  return node.outerHTML||"";
}
function placeCaretAtEndOfNode(index){
  const ed=$("editor");
  const node=ed.childNodes[Math.max(0,Math.min(index,ed.childNodes.length-1))];
  if(!node){ed.focus();return}
  const range=document.createRange();
  range.selectNodeContents(node);
  range.collapse(false);
  const sel=getSelection();
  sel.removeAllRanges();
  sel.addRange(range);
  savedRange=range.cloneRange();
  ed.focus();
}
function pushOverflowToNextPage(){
  const s=current(),page=currentPage(),ed=$("editor");
  normalizeEditorTopLevel();

  const moved=[];
  while(editorOverflows() && ed.childNodes.length>1){
    const node=ed.lastChild;
    moved.unshift(nodeHTML(node));
    node.remove();
  }
  if(!moved.length)return false;

  page.content=ed.innerHTML;

  let next=s.pages[s.currentPageIndex+1];
  if(!next || !next.autoGenerated){
    next=newPage(s.currentPageIndex+2,true);
    s.pages.splice(s.currentPageIndex+1,0,next);
  }
  next.content=moved.join("")+(next.content||"");
  renumberPages();

  const movedCount=moved.length;
  s.currentPageIndex++;
  persist();
  renderAll();
  requestAnimationFrame(()=>placeCaretAtEndOfNode(movedCount-1));
  return true;
}
function pullContentBackIntoCurrentPage(){
  const s=current(),ed=$("editor");
  let next=s.pages[s.currentPageIndex+1];
  if(!next || !next.autoGenerated || next.title || next.subtitle)return false;

  let changed=false;
  while(next && next.autoGenerated && !next.title && !next.subtitle && next.content){
    const box=document.createElement("div");
    box.innerHTML=next.content;
    const first=box.firstChild;
    if(!first)break;

    const clone=first.cloneNode(true);
    ed.appendChild(clone);
    if(editorOverflows()){
      clone.remove();
      break;
    }

    first.remove();
    currentPage().content=ed.innerHTML;
    next.content=box.innerHTML;
    changed=true;

    if(!next.content.trim()){
      s.pages.splice(s.currentPageIndex+1,1);
      renumberPages();
      next=s.pages[s.currentPageIndex+1];
      if(!next || !next.autoGenerated)break;
    }
  }

  if(changed){
    persist();
    $("pageNavLabel").textContent=`PAGE ${String(s.currentPageIndex+1).padStart(2,"0")} / ${String(s.pages.length).padStart(2,"0")}`;
    renderSlots();
  }
  return changed;
}
function handleEditorInput(){
  rememberSelection();

  const p=currentPage();
  p.content=$("editor").innerHTML;
  current().updatedAt=new Date().toISOString();

  if(pushOverflowToNextPage())return;

  if(String(lastEditorInputType).startsWith("delete")){
    pullContentBackIntoCurrentPage();
  }

  persist();
  updateCount();
  renderSlots();
}
function reflowAllAutoPagesFromCurrentSlot(){
  if(isPaginating)return;
  isPaginating=true;
  const s=current(),originalIndex=s.currentPageIndex;

  try{
    saveCurrent(false);

    for(let i=0;i<s.pages.length;i++){
      s.currentPageIndex=i;
      const p=s.pages[i];
      $("titleInput").value=p.title||"";
      $("subtitleInput").value=p.subtitle||"";
      $("editor").innerHTML=p.content||"";
      applyTypography();
      normalizeEditorTopLevel();

      const moved=[];
      while(editorOverflows() && $("editor").childNodes.length>1){
        const node=$("editor").lastChild;
        moved.unshift(nodeHTML(node));
        node.remove();
      }
      p.content=$("editor").innerHTML;

      if(moved.length){
        let next=s.pages[i+1];
        if(!next || !next.autoGenerated){
          next=newPage(i+2,true);
          s.pages.splice(i+1,0,next);
        }
        next.content=moved.join("")+(next.content||"");
      }
    }

    for(let i=0;i<s.pages.length-1;i++){
      let next=s.pages[i+1];
      if(!next?.autoGenerated || next.title || next.subtitle)continue;

      s.currentPageIndex=i;
      const p=s.pages[i];
      $("titleInput").value=p.title||"";
      $("subtitleInput").value=p.subtitle||"";
      $("editor").innerHTML=p.content||"";
      applyTypography();

      while(next && next.autoGenerated && !next.title && !next.subtitle && next.content){
        const box=document.createElement("div");
        box.innerHTML=next.content;
        const first=box.firstChild;
        if(!first)break;

        const clone=first.cloneNode(true);
        $("editor").appendChild(clone);
        if(editorOverflows()){
          clone.remove();
          break;
        }

        first.remove();
        p.content=$("editor").innerHTML;
        next.content=box.innerHTML;

        if(!next.content.trim()){
          s.pages.splice(i+1,1);
          next=s.pages[i+1];
          if(!next || !next.autoGenerated)break;
        }
      }
    }

    renumberPages();
    s.currentPageIndex=Math.min(originalIndex,s.pages.length-1);
    persist();
  }finally{
    isPaginating=false;
    renderAll();
  }
}

document.addEventListener("selectionchange",()=>{
  const sel=getSelection();
  if(!sel?.rangeCount)return;
  const r=sel.getRangeAt(0);
  if($("editor").contains(r.commonAncestorContainer)) savedRange=r.cloneRange();
});
function rememberSelection(){const sel=getSelection();if(sel?.rangeCount){const r=sel.getRangeAt(0);if($("editor").contains(r.commonAncestorContainer))savedRange=r.cloneRange()}}
$("editor").addEventListener("mouseup",rememberSelection);$("editor").addEventListener("keyup",rememberSelection);$("editor").addEventListener("input",rememberSelection);
function restoreSelection(){if(!savedRange)return false;const s=getSelection();s.removeAllRanges();s.addRange(savedRange);return true}
function exec(cmd,val=null){restoreSelection();$("editor").focus();document.execCommand(cmd,false,val);rememberSelection();scheduleSave()}
document.querySelectorAll("[data-cmd]").forEach(b=>{
  b.addEventListener("mousedown",e=>e.preventDefault());
  b.onclick=()=>{
    const cmd=b.dataset.cmd;

    if(["indent","outdent"].includes(cmd)){
      applyParagraphIndent(cmd==="indent"?1:-1);
      return;
    }

    if(["justifyLeft","justifyCenter","justifyRight","justifyFull"].includes(cmd)){
      applyParagraphAlignment(cmd);
      return;
    }

    if(["insertUnorderedList","insertOrderedList","undo","redo"].includes(cmd)){
      restoreSelection();
      exec(cmd);
      return;
    }

    if(!hasSelection()) return alert("수정할 글자를 먼저 드래그해주세요.");
    exec(cmd);
  };
});


function selectedBlocks(){
  restoreSelection();
  const sel=getSelection();
  if(!sel?.rangeCount) return [];
  const range=sel.getRangeAt(0);
  if(!$("editor").contains(range.commonAncestorContainer)) return [];

  const blocks=[];
  const candidates=$("editor").querySelectorAll("p,div,blockquote,li,h1,h2,h3");
  candidates.forEach(el=>{
    try{
      if(range.intersectsNode(el) && !el.classList.contains("paragraph-divider")) blocks.push(el);
    }catch{}
  });

  if(!blocks.length){
    let node=range.startContainer.nodeType===3?range.startContainer.parentNode:range.startContainer;
    while(node && node!==$("editor")){
      if(/^(P|DIV|BLOCKQUOTE|LI|H1|H2|H3)$/.test(node.tagName)){blocks.push(node);break}
      node=node.parentNode;
    }
  }
  return [...new Set(blocks)];
}

function applyParagraphIndent(direction){
  restoreSelection();
  const sel=getSelection();
  if(!sel?.rangeCount)return;

  const range=sel.getRangeAt(0);

  // If caret/selection is in a list item, use real list nesting behavior.
  let node=range.startContainer.nodeType===3
    ? range.startContainer.parentElement
    : range.startContainer;

  let listItem=null;
  while(node && node!==$("editor")){
    if(node.tagName==="LI"){
      listItem=node;
      break;
    }
    node=node.parentElement;
  }

  if(listItem){
    // List indentation should move the whole list item.
    restoreSelection();
    document.execCommand(direction>0?"indent":"outdent",false,null);
    rememberSelection();
    scheduleSave();
    return;
  }

  // Normal text: indent only the first line of the paragraph,
  // approximately 2–3 spaces.
  const blocks=selectedBlocks();
  if(!blocks.length){
    return alert("들여쓰기할 문단에 커서를 두거나 문단을 선택해주세요.");
  }

  blocks.forEach(el=>{
    if(el.tagName==="LI")return;

    const current=parseFloat(el.style.textIndent)||0;
    const step=0.8; // compact first-line indent, close to a few space presses
    const next=Math.max(0,current + direction*step);
    el.style.textIndent=next===0?"":next+"em";
  });

  scheduleSave();
}
function applyParagraphAlignment(cmd){
  const map={justifyLeft:"left",justifyCenter:"center",justifyRight:"right",justifyFull:"justify"};
  const blocks=selectedBlocks();
  if(!blocks.length) return alert("정렬할 문단에 커서를 두거나 문단을 선택해주세요.");
  blocks.forEach(el=>el.style.textAlign=map[cmd]);
  scheduleSave();
}

$("fontFamily").onchange=e=>{
  if(!hasSelection()) return;
  applySelectionStyle("fontFamily",e.target.value);requestAnimationFrame(reflowAllAutoPagesFromCurrentSlot);
};
$("fontSize").onchange=e=>{
  if(!hasSelection()) return;
  const pt=Math.max(6,Math.min(54,Number(e.target.value)||12));
  applySelectionStyle("fontSize",pt+"pt");requestAnimationFrame(reflowAllAutoPagesFromCurrentSlot);
};




$("applyFontSectionBtn").onclick=()=>{
  const s=current();
  s.typography=s.typography||defaultTypography();
  s.typography.fontFamily=$("fontFamily").value||"Pretendard";
  s.typography.fontSizePt=Math.max(6,Math.min(54,Number($("fontSize").value)||12));
  s.typography.textColor=$("textColor").value||"#3f3d3b";

  // Remove page-level overrides for these global font fields,
  // so every page follows the slot-wide setting.
  s.pages.forEach(p=>{
    p.pageTypography=p.pageTypography||{};
    delete p.pageTypography.fontFamily;
    delete p.pageTypography.fontSizePt;
    delete p.pageTypography.textColor;
  });

  persist();applyTypography();syncControls();
  requestAnimationFrame(reflowAllAutoPagesFromCurrentSlot);
};



$("textColor").addEventListener("change",()=>{
  if(!hasSelection())return;
  applySelectionStyle("color",$("textColor").value);
});
$("applyHighlightBtn").onclick=()=>{
  if(!hasSelection())return alert("형광펜을 적용할 부분을 먼저 드래그해주세요.");
  applyHighlightMark($("highlightColor").value);
};

$("removeHighlightBtn").onclick=()=>{
  if(!hasSelection())return alert("형광펜을 지울 부분을 먼저 드래그해주세요.");
  removeHighlightMarksInSelection();
};



function selectedTextSlices(){
  restoreSelection();
  const sel=getSelection();
  if(!sel?.rangeCount || sel.isCollapsed)return [];

  const range=sel.getRangeAt(0);
  const editor=$("editor");
  if(!editor.contains(range.commonAncestorContainer))return [];

  const walker=document.createTreeWalker(
    editor,
    NodeFilter.SHOW_TEXT,
    {
      acceptNode(node){
        if(!node.nodeValue)return NodeFilter.FILTER_REJECT;
        try{
          return range.intersectsNode(node)
            ? NodeFilter.FILTER_ACCEPT
            : NodeFilter.FILTER_REJECT;
        }catch{
          return NodeFilter.FILTER_REJECT;
        }
      }
    }
  );

  const slices=[];
  let node;
  while((node=walker.nextNode())){
    let start=0,end=node.nodeValue.length;

    if(node===range.startContainer)start=range.startOffset;
    if(node===range.endContainer)end=range.endOffset;

    if(start<end){
      slices.push({node,start,end});
    }
  }
  return slices;
}

function splitTextSlice(node,start,end){
  let selected=node;

  if(end<selected.nodeValue.length){
    selected.splitText(end);
  }
  if(start>0){
    selected=selected.splitText(start);
  }
  return selected;
}

function makeHighlightSpan(textNode,color){
  const span=document.createElement("span");
  span.className="text-highlight";
  span.dataset.highlight="1";
  span.style.backgroundColor=color;
  span.style.color="inherit";
  textNode.parentNode.insertBefore(span,textNode);
  span.appendChild(textNode);
  return span;
}

function applyHighlightMark(color){
  const slices=selectedTextSlices();
  if(!slices.length)return false;

  // Process from the end so splitText offsets stay stable.
  const created=[];
  for(let i=slices.length-1;i>=0;i--){
    const {node,start,end}=slices[i];

    // Never wrap block elements: only the exact text fragment is wrapped.
    const selectedNode=splitTextSlice(node,start,end);

    // If already highlighted, just update that small span's color.
    const parentHighlight=selectedNode.parentElement?.closest("span.text-highlight[data-highlight='1']");
    if(parentHighlight && parentHighlight.childNodes.length===1){
      parentHighlight.style.backgroundColor=color;
      created.push(parentHighlight);
      continue;
    }

    created.push(makeHighlightSpan(selectedNode,color));
  }

  // Restore selection around the same logical highlighted text.
  if(created.length){
    const sel=getSelection();
    const range=document.createRange();
    const first=created[created.length-1];
    const last=created[0];
    range.setStartBefore(first);
    range.setEndAfter(last);
    sel.removeAllRanges();
    sel.addRange(range);
    savedRange=range.cloneRange();
  }

  scheduleSave();
  return true;
}

function normalizeLegacyHighlights(){
  const editor=$("editor");

  // Convert old MARK / background spans into leaf highlight spans around text nodes.
  const legacy=[...editor.querySelectorAll(
    "mark.text-highlight, span.text-highlight:not([data-highlight='1'])"
  )];

  legacy.forEach(wrapper=>{
    const bg=wrapper.style.backgroundColor || wrapper.style.background || "#fff2a8";
    const textNodes=[];
    const walker=document.createTreeWalker(wrapper,NodeFilter.SHOW_TEXT);
    let n;
    while((n=walker.nextNode())){
      if(n.nodeValue)textNodes.push(n);
    }

    // Wrap each text node independently, preserving all other inline formatting.
    textNodes.forEach(textNode=>{
      if(textNode.parentElement?.matches("span.text-highlight[data-highlight='1']"))return;
      makeHighlightSpan(textNode,bg);
    });

    // Remove only the legacy wrapper itself, preserving its children.
    if(wrapper.isConnected){
      const parent=wrapper.parentNode;
      if(parent){
        while(wrapper.firstChild)parent.insertBefore(wrapper.firstChild,wrapper);
        wrapper.remove();
      }
    }
  });
}

function removeHighlightMarksInSelection(){
  normalizeLegacyHighlights();

  const slices=selectedTextSlices();
  if(!slices.length)return false;

  const processed=new Set();

  // Each highlight span is a leaf containing only one text node,
  // so partial removal can be split safely without touching paragraphs.
  for(let i=slices.length-1;i>=0;i--){
    const {node,start,end}=slices[i];
    const highlight=node.parentElement?.closest("span.text-highlight[data-highlight='1']");
    if(!highlight || processed.has(highlight))continue;
    processed.add(highlight);

    const textNode=highlight.firstChild;
    if(!textNode || textNode.nodeType!==Node.TEXT_NODE)continue;

    // Calculate overlap within this leaf highlight span.
    let localStart=0,localEnd=textNode.nodeValue.length;
    if(node===textNode){
      localStart=start;
      localEnd=end;
    }

    if(localStart<=0 && localEnd>=textNode.nodeValue.length){
      // Whole highlight span selected: unwrap it.
      const parent=highlight.parentNode;
      parent.insertBefore(textNode,highlight);
      highlight.remove();
      continue;
    }

    const text=textNode.nodeValue;
    const before=text.slice(0,localStart);
    const middle=text.slice(localStart,localEnd);
    const after=text.slice(localEnd);

    const frag=document.createDocumentFragment();

    if(before){
      const beforeSpan=highlight.cloneNode(false);
      beforeSpan.textContent=before;
      frag.appendChild(beforeSpan);
    }

    if(middle){
      frag.appendChild(document.createTextNode(middle));
    }

    if(after){
      const afterSpan=highlight.cloneNode(false);
      afterSpan.textContent=after;
      frag.appendChild(afterSpan);
    }

    highlight.replaceWith(frag);
  }

  // Merge adjacent plain text/highlight spans where possible.
  $("editor").normalize();

  scheduleSave();
  return true;
}

function resetPageFormatting(){
  const ed=$("editor");
  // unwrap FONT/SPAN wrappers while keeping semantic paragraphs/headings/lists/dividers
  [...ed.querySelectorAll("font,span")].forEach(el=>{
    const parent=el.parentNode;
    while(el.firstChild) parent.insertBefore(el.firstChild,el);
    el.remove();
  });
  [...ed.querySelectorAll("*")].forEach(el=>{
    if(el.classList?.contains("paragraph-divider")) return;
    el.removeAttribute("style");
    el.removeAttribute("color");
    el.removeAttribute("face");
    el.removeAttribute("size");
  });
  currentPage().pageTypography={
    fontFamily:"Pretendard",
    fontSizePt:12,
    textColor:"#3f3d3b",
    highlightColor:"#fff2a8",
    letterSpacing:0,
    lineHeight:1.25,
    paragraphSpacing:0,
    
    widthScale:100,
    fontWeight:"400",
    fontStyle:"normal",
    textDecoration:"",
    textAlign:"left"
  };
  applyTypography();syncControls();scheduleSave();
}
$("resetFormatBtn").onclick=resetPageFormatting;

function textNodesUnder(root){
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});
  const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);return nodes;
}
function applyStyleToAllText(prop,value){
  const nodes=textNodesUnder($("editor"));
  nodes.forEach(node=>{
    if(node.parentElement?.classList.contains("paragraph-divider")) return;
    const span=document.createElement("span");
    span.style[prop]=value;
    node.parentNode.insertBefore(span,node);span.appendChild(node);
  });
  scheduleSave();
}
function clearStyleFromAllText(prop){
  $("editor").querySelectorAll("[style]").forEach(el=>{
    if(el.classList.contains("paragraph-divider")) return;
    el.style[prop]="";
    if(!el.getAttribute("style")?.trim()) el.removeAttribute("style");
  });
  scheduleSave();
}

$("blockStyle").onchange=e=>exec("formatBlock",e.target.value);
$("linkBtn").onclick=()=>{
  rememberSelection();
  let selected="";
  try{restoreSelection();selected=getSelection()?.toString()||""}catch{}
  $("linkNameInput").value=selected;
  $("linkUrlInput").value="https://";
  $("linkModal").hidden=false;
};

document.querySelectorAll("[data-close-link]").forEach(x=>x.onclick=()=>{$("linkModal").hidden=true});
$("insertLinkBtn").onclick=()=>{
  const name=$("linkNameInput").value.trim(),url=$("linkUrlInput").value.trim();
  if(!name)return alert("링크명을 입력해주세요.");
  if(!url)return alert("링크 주소를 입력해주세요.");
  restoreSelection();
  const sel=getSelection();if(!sel?.rangeCount)return;
  const range=sel.getRangeAt(0);
  if(!$("editor").contains(range.commonAncestorContainer))return alert("본문에서 링크를 넣을 위치를 선택해주세요.");
  const a=document.createElement("a");a.href=url;a.textContent=name;a.target="_blank";a.rel="noopener noreferrer";
  range.deleteContents();range.insertNode(a);
  const caret=document.createRange();caret.setStartAfter(a);caret.collapse(true);
  sel.removeAllRanges();sel.addRange(caret);savedRange=caret.cloneRange();
  $("linkModal").hidden=true;scheduleSave();
};
$("clearFormatBtn").onclick=()=>{
  if(!hasSelection()) return alert("서식을 지울 글자를 먼저 선택해주세요. 페이지 전체를 초기화하려면 ‘기본 서식으로’를 사용해주세요.");
  exec("removeFormat");
};


function toggleWholeStyle(prop,onValue,offValue){
  const ed=$("editor");
  const currentValue=ed.style[prop];
  const next=currentValue===onValue?offValue:onValue;
  ed.style[prop]=next;
  currentPage().pageTypography[prop]=next;
  persist();
}
function toggleWholeTextDecoration(kind){
  const ed=$("editor");
  let currentDeco=ed.style.textDecoration||"";
  const has=currentDeco.includes(kind);
  let parts=currentDeco.split(/\s+/).filter(Boolean).filter(x=>x!==kind);
  if(!has) parts.push(kind);
  const next=parts.join(" ");
  ed.style.textDecoration=next;
  currentPage().pageTypography.textDecoration=next;
  persist();
}

function hasSelection(){restoreSelection();const s=getSelection();return !!(s&&s.rangeCount&&!s.isCollapsed&&$("editor").contains(s.getRangeAt(0).commonAncestorContainer))}
function applySelectionStyle(prop,value){
  restoreSelection();
  const sel=getSelection();
  if(!sel?.rangeCount || sel.isCollapsed) return false;
  const range=sel.getRangeAt(0);
  if(!$("editor").contains(range.commonAncestorContainer)) return false;

  const span=document.createElement("span");
  span.className="selection-style";
  span.style[prop]=value;

  try{
    range.surroundContents(span);
  }catch{
    const frag=range.extractContents();
    span.appendChild(frag);
    range.insertNode(span);
  }

  const newRange=document.createRange();
  newRange.selectNodeContents(span);
  sel.removeAllRanges();
  sel.addRange(newRange);
  savedRange=newRange.cloneRange();
  scheduleSave();
  return true;
}
function applySelectionWidthScale(percent){
  restoreSelection();
  const s=getSelection(); if(!s?.rangeCount||s.isCollapsed)return false;
  const r=s.getRangeAt(0),span=document.createElement("span");
  span.style.display="inline-block";
  span.style.transform=`scaleX(${percent/100})`;
  span.style.transformOrigin="left center";
  try{r.surroundContents(span)}catch{const f=r.extractContents();span.appendChild(f);r.insertNode(span)}
  rememberSelection();scheduleSave();return true;
}
function effectiveTypography(){
  const merged={...defaultTypography(),...current().typography,...(currentPage().pageTypography||{})};
  if(merged.fontSizePt==null && merged.fontSize!=null) merged.fontSizePt=Math.round((Number(merged.fontSize)*0.75)*2)/2;
  return merged;
}
function applyTypography(){
  const t=effectiveTypography();
  const ed=$("editor");
  ed.style.setProperty("--editor-font",`"${t.fontFamily}"`);
  ed.style.fontFamily=t.fontFamily;
  $("titleInput").style.fontFamily=t.fontFamily;
  $("subtitleInput").style.fontFamily=t.fontFamily;
  ed.style.setProperty("--editor-size",(t.fontSizePt??12)+"pt");
  ed.style.setProperty("--editor-letter",(t.letterSpacing/100)+"em");
  ed.style.setProperty("--editor-line",String(t.lineHeight??1.45));
  ed.style.setProperty("--editor-para",(t.paragraphSpacing??0)+"px");
  ed.style.setProperty("--editor-color",t.textColor||"#3f3d3b");
  ed.style.color=t.textColor||"#3f3d3b";
  ed.style.fontWeight=t.fontWeight||"400";
  ed.style.fontStyle=t.fontStyle||"normal";
  ed.style.textDecoration=t.textDecoration||"";
  ed.style.textAlign=t.textAlign||"left";
  const scale=(t.widthScale??100)/100;
  ed.style.transform=`scaleX(${scale})`;
  ed.style.transformOrigin="left top";
  ed.style.width=`${100/scale}%`;
}

function bindRange(id,key,format){
  $(id).oninput=e=>{
    const value=format(Number(e.target.value));
    updateSpacingOutputsOnly();

    if(hasSelection()){
      if(key==="letterSpacing") applySelectionStyle("letterSpacing",(value/100)+"em");
      else if(key==="lineHeight") applySelectionStyle("lineHeight",String(value));
      else if(key==="paragraphSpacing"){
        const blocks=selectedBlocks();
        blocks.forEach(el=>el.style.marginBottom=value+"px");
        scheduleSave();
      }
      else if(key==="widthScale") applySelectionWidthScale(value);
      return;
    }

    // No selection = slot-wide setting shared by every page.
    const s=current();
    s.typography=s.typography||defaultTypography();
    s.typography[key]=value;
    s.pages.forEach(p=>{
      p.pageTypography=p.pageTypography||{};
      delete p.pageTypography[key];
    });
    persist();
    applyTypography();
    syncControls();
    requestAnimationFrame(reflowAllAutoPagesFromCurrentSlot);
  };
}
function updateSpacingOutputsOnly(){
  $("letterSpacingOut").textContent=(Number($("letterSpacing").value)/100)+"em";
  $("lineHeightOut").textContent=(Number($("lineHeight").value)/100).toFixed(2).replace(/0+$/,"").replace(/\.$/,"");
  $("paragraphSpacingOut").textContent=$("paragraphSpacing").value+"px";
  $("widthScaleOut").textContent=$("widthScale").value+"%";
}

bindRange("letterSpacing","letterSpacing",v=>v);
bindRange("lineHeight","lineHeight",v=>v/100);
bindRange("paragraphSpacing","paragraphSpacing",v=>v);
bindRange("widthScale","widthScale",v=>v);

function syncControls(){
  const t=effectiveTypography(),b=current().background;
  if(b.effectAutoColor==null)b.effectAutoColor=true;
  if(b.paperBorderAutoColor==null)b.paperBorderAutoColor=true;
  if(b.paperFrameAutoColor==null)b.paperFrameAutoColor=true;
  $("fontFamily").value=t.fontFamily;$("fontSize").value=t.fontSizePt??12;
  $("textColor").value=t.textColor||"#3f3d3b";
  $("highlightColor").value=t.highlightColor||"#fff2a8";
  $("letterSpacing").value=t.letterSpacing;$("letterSpacingOut").textContent=(t.letterSpacing/100)+"em";
  $("lineHeight").value=Math.round(t.lineHeight*100);$("lineHeightOut").textContent=String(t.lineHeight);
  $("paragraphSpacing").value=t.paragraphSpacing;$("paragraphSpacingOut").textContent=t.paragraphSpacing+"px";
  $("widthScale").value=t.widthScale??100;$("widthScaleOut").textContent=(t.widthScale??100)+"%";
  $("solidColor").value=b.solid;$("grad1").value=b.grad1;$("grad2").value=b.grad2;$("gradAngle").value=b.angle;$("gradAngleOut").textContent=b.angle+"°";
  $("bgSize").value=b.size;$("bgBrightness").value=b.brightness;$("bgBrightnessOut").textContent=b.brightness+"%";
  $("effectOpacity").value=b.effectOpacity;$("effectOpacityOut").textContent=b.effectOpacity+"%";
  $("effectColor").value=b.effectColor||"#8f887f";
  $("effectAutoColor").checked=!!b.effectAutoColor;
  $("paperBorderAutoColor").checked=!!b.paperBorderAutoColor;
  $("paperFrameAutoColor").checked=!!b.paperFrameAutoColor;
  $("effectColor").closest(".field")?.classList.toggle("auto-color-active",!!b.effectAutoColor);
  $("paperBorderColor").closest(".field")?.classList.toggle("auto-color-active",!!b.paperBorderAutoColor);
  $("paperFrameColor").closest(".field")?.classList.toggle("auto-color-active",!!b.paperFrameAutoColor);
  $("paperBorderOpacity").value=b.paperBorderOpacity??100;$("paperBorderOpacityOut").textContent=(b.paperBorderOpacity??100)+"%";
  $("paperFrameOpacity").value=b.paperFrameOpacity??100;$("paperFrameOpacityOut").textContent=(b.paperFrameOpacity??100)+"%";
  $("paperBorderStyle").value=b.paperBorderStyle||"none";
  $("paperBorderColor").value=b.paperBorderColor||"#d8d2c8";
  $("paperBorderWidth").value=b.paperBorderWidth??1;$("paperBorderWidthOut").textContent=(b.paperBorderWidth??1)+"px";
  $("paperInnerInset").value=b.paperInnerInset??0;$("paperInnerInsetOut").textContent=(b.paperInnerInset??0)+"px";
  $("paperFrameStyle").value=b.paperFrameStyle||"none";
  $("paperFrameColor").value=b.paperFrameColor||"#bdb5a8";
  $("paperShadow").value=b.paperShadow??16;$("paperShadowOut").textContent=String(b.paperShadow??16);
  $("dividerSize").value=b.dividerSize??16;$("dividerSizeOut").textContent=(b.dividerSize??16)+"px";
  $("dividerMargin").value=b.dividerMargin??18;$("dividerMarginOut").textContent=(b.dividerMargin??18)+"px";
  document.querySelectorAll(".bg-mode").forEach(x=>x.classList.toggle("active",x.dataset.mode===b.mode));
  document.querySelectorAll(".effect-btn").forEach(x=>x.classList.toggle("active",x.dataset.effect===b.effect));
}

document.querySelectorAll('[data-panel="text"] button, [data-panel="text"] select, [data-panel="text"] input')
  .forEach(el=>{
    el.addEventListener("pointerdown",()=>rememberSelection(),true);
  });
document.querySelectorAll(".tab").forEach(tab=>{
  tab.addEventListener("click",()=>{
    document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===tab));
    document.querySelectorAll(".panel-body").forEach(panel=>{
      panel.classList.toggle("active",panel.dataset.panel===tab.dataset.tab);
    });
    if(tab.dataset.tab==="background")syncBackgroundOptionPanels();
  });
});

function syncBackgroundOptionPanels(){
  const mode=current().background.mode||"solid";
  document.querySelectorAll(".bg-options").forEach(p=>p.classList.toggle("active",p.dataset.bgOptions===mode));
}
document.querySelectorAll(".bg-mode").forEach(b=>b.onclick=()=>{
  current().background.mode=b.dataset.mode;
  refreshAutomaticDecorationColors();
  persist();syncControls();syncBackgroundOptionPanels();applyBackground();
});
["solidColor","grad1","grad2"].forEach(id=>$(id).oninput=e=>{const map={solidColor:"solid",grad1:"grad1",grad2:"grad2"};current().background[map[id]]=e.target.value;persist();applyBackground()});
$("gradAngle").oninput=e=>{current().background.angle=Number(e.target.value);persist();syncControls();applyBackground()};
$("bgSize").onchange=e=>{current().background.size=e.target.value;persist();applyBackground()};
$("bgBrightness").oninput=e=>{current().background.brightness=Number(e.target.value);persist();syncControls();applyBackground()};

document.querySelectorAll(".effect-btn").forEach(b=>b.onclick=()=>{current().background.effect=b.dataset.effect;persist();syncControls();applyBackground()});
$("effectOpacity").oninput=e=>{current().background.effectOpacity=Number(e.target.value);persist();syncControls();applyBackground()};
$("effectColor").oninput=e=>{
  current().background.effectColor=e.target.value;
  current().background.effectAutoColor=false;
  $("effectAutoColor").checked=false;
  persist();syncControls();applyBackground();
};
$("effectAutoColor").onchange=e=>{
  current().background.effectAutoColor=e.target.checked;
  if(e.target.checked)refreshAutomaticDecorationColors();
  persist();syncControls();applyBackground();
};

$("paperBorderStyle").onchange=e=>{current().background.paperBorderStyle=e.target.value;persist();applyBackground()};
$("paperBorderColor").oninput=e=>{
  current().background.paperBorderColor=e.target.value;
  current().background.paperBorderAutoColor=false;
  $("paperBorderAutoColor").checked=false;
  persist();syncControls();applyBackground();
};
$("paperBorderAutoColor").onchange=e=>{
  current().background.paperBorderAutoColor=e.target.checked;
  if(e.target.checked)refreshAutomaticDecorationColors();
  persist();syncControls();applyBackground();
};
$("paperBorderWidth").oninput=e=>{current().background.paperBorderWidth=Number(e.target.value);$("paperBorderWidthOut").textContent=e.target.value+"px";persist();applyBackground()};
$("paperInnerInset").oninput=e=>{current().background.paperInnerInset=Number(e.target.value);$("paperInnerInsetOut").textContent=e.target.value+"px";persist();applyBackground()};
$("paperFrameStyle").onchange=e=>{current().background.paperFrameStyle=e.target.value;persist();applyBackground()};
$("paperFrameColor").oninput=e=>{
  current().background.paperFrameColor=e.target.value;
  current().background.paperFrameAutoColor=false;
  $("paperFrameAutoColor").checked=false;
  persist();syncControls();applyBackground();
};
$("paperFrameAutoColor").onchange=e=>{
  current().background.paperFrameAutoColor=e.target.checked;
  if(e.target.checked)refreshAutomaticDecorationColors();
  persist();syncControls();applyBackground();
};
$("paperShadow").oninput=e=>{current().background.paperShadow=Number(e.target.value);$("paperShadowOut").textContent=e.target.value;persist();applyBackground()};
$("paperBorderOpacity").oninput=e=>{current().background.paperBorderOpacity=Number(e.target.value);$("paperBorderOpacityOut").textContent=e.target.value+"%";persist();applyBackground()};
$("paperFrameOpacity").oninput=e=>{current().background.paperFrameOpacity=Number(e.target.value);$("paperFrameOpacityOut").textContent=e.target.value+"%";persist();applyBackground()};

$("dividerSize").oninput=e=>{current().background.dividerSize=Number(e.target.value);persist();syncControls()};
$("dividerMargin").oninput=e=>{current().background.dividerMargin=Number(e.target.value);persist();syncControls()};


function hexToRgbSimple(hex){
  const h=String(hex||"#ffffff").replace("#","");
  const full=h.length===3?h.split("").map(x=>x+x).join(""):h.padEnd(6,"f");
  const n=parseInt(full,16);
  return {r:(n>>16)&255,g:(n>>8)&255,b:n&255};
}
function rgbToHexSimple({r,g,b}){
  const c=v=>Math.max(0,Math.min(255,Math.round(v))).toString(16).padStart(2,"0");
  return "#"+c(r)+c(g)+c(b);
}
function mixRgb(a,b,t){return {r:a.r+(b.r-a.r)*t,g:a.g+(b.g-a.g)*t,b:a.b+(b.b-a.b)*t}}
function averageHex(a,b){
  const x=hexToRgbSimple(a),y=hexToRgbSimple(b);
  return rgbToHexSimple({r:(x.r+y.r)/2,g:(x.g+y.g)/2,b:(x.b+y.b)/2});
}
function ambientFromColor(hex){
  const c=hexToRgbSimple(hex),lum=c.r*.299+c.g*.587+c.b*.114;
  const neutral=lum>165?{r:166,g:161,b:154}:{r:235,g:232,b:226};
  return rgbToHexSimple(mixRgb(c,neutral,.48));
}

function rgbToHslSimple({r,g,b}){
  r/=255; g/=255; b/=255;
  const max=Math.max(r,g,b), min=Math.min(r,g,b);
  let h=0,s=0,l=(max+min)/2;
  if(max!==min){
    const d=max-min;
    s=l>.5?d/(2-max-min):d/(max+min);
    switch(max){
      case r: h=(g-b)/d+(g<b?6:0);break;
      case g: h=(b-r)/d+2;break;
      case b: h=(r-g)/d+4;break;
    }
    h/=6;
  }
  return {h:h*360,s:s*100,l:l*100};
}
function hslToHexSimple({h,s,l}){
  h=((h%360)+360)%360; s/=100; l/=100;
  const c=(1-Math.abs(2*l-1))*s;
  const x=c*(1-Math.abs((h/60)%2-1));
  const m=l-c/2;
  let rp=0,gp=0,bp=0;
  if(h<60){rp=c;gp=x}
  else if(h<120){rp=x;gp=c}
  else if(h<180){gp=c;bp=x}
  else if(h<240){gp=x;bp=c}
  else if(h<300){rp=x;bp=c}
  else{rp=c;bp=x}
  return rgbToHexSimple({r:(rp+m)*255,g:(gp+m)*255,b:(bp+m)*255});
}
function getDocumentBaseColor(){
  const b=current().background;
  if(b.mode==="solid") return b.solid||"#ffffff";
  if(b.mode==="gradient") return averageHex(b.grad1||"#ffffff",b.grad2||"#e8e2da");
  if(b.mode==="image" && b.imageAverageColor) return b.imageAverageColor;
  if(b.ambientColor) return b.ambientColor;
  return b.solid||"#ffffff";
}
function autoAccentColor(baseHex,kind="effect"){
  const hsl=rgbToHslSimple(hexToRgbSimple(baseHex));
  const darkBase=hsl.l<45;
  const veryLight=hsl.l>82;

  if(kind==="effect"){
    // Similar hue, slightly stronger saturation and contrasting lightness.
    return hslToHexSimple({
      h:hsl.h,
      s:Math.min(55,Math.max(16,hsl.s*0.85+12)),
      l:darkBase?Math.min(82,hsl.l+32):(veryLight?Math.max(30,hsl.l-42):Math.max(28,hsl.l-28))
    });
  }

  if(kind==="border"){
    return hslToHexSimple({
      h:hsl.h,
      s:Math.min(42,Math.max(10,hsl.s*0.65+8)),
      l:darkBase?Math.min(76,hsl.l+26):Math.max(34,hsl.l-30)
    });
  }

  // frame: slightly shifted hue for separation, still harmonious.
  return hslToHexSimple({
    h:hsl.h+10,
    s:Math.min(48,Math.max(12,hsl.s*0.72+10)),
    l:darkBase?Math.min(80,hsl.l+30):Math.max(31,hsl.l-34)
  });
}
function refreshAutomaticDecorationColors(){
  const b=current().background;
  const base=getDocumentBaseColor();

  if(b.effectAutoColor){
    b.effectColor=autoAccentColor(base,"effect");
  }
  if(b.paperBorderAutoColor){
    b.paperBorderColor=autoAccentColor(base,"border");
  }
  if(b.paperFrameAutoColor){
    b.paperFrameColor=autoAccentColor(base,"frame");
  }

  if($("effectColor")) $("effectColor").value=b.effectColor||"#8f887f";
  if($("paperBorderColor")) $("paperBorderColor").value=b.paperBorderColor||"#d8d2c8";
  if($("paperFrameColor")) $("paperFrameColor").value=b.paperFrameColor||"#bdb5a8";
}

function applyAmbientColor(hex){
  const ambient=ambientFromColor(hex);
  current().background.ambientColor=ambient;
  document.documentElement.style.setProperty("--work",ambient);
  document.body.style.backgroundColor=ambient;
  document.querySelector(".workspace").style.backgroundColor=ambient;
}
function computeImageAverageColor(file){
  return new Promise(resolve=>{
    const reader=new FileReader();
    reader.onload=()=>{
      const img=new Image();
      img.onload=()=>{
        const canvas=document.createElement("canvas");
        canvas.width=32;canvas.height=32;
        const ctx=canvas.getContext("2d",{willReadFrequently:true});
        ctx.drawImage(img,0,0,32,32);
        try{
          const data=ctx.getImageData(0,0,32,32).data;
          let r=0,g=0,b=0,n=0;
          for(let i=0;i<data.length;i+=4){
            if(data[i+3]<40) continue;
            r+=data[i];g+=data[i+1];b+=data[i+2];n++;
          }
          resolve(n?rgbToHexSimple({r:r/n,g:g/n,b:b/n}):"#dedbd4");
        }catch{resolve("#dedbd4")}
      };
      img.onerror=()=>resolve("#dedbd4");
      img.src=reader.result;
    };
    reader.onerror=()=>resolve("#dedbd4");
    reader.readAsDataURL(file);
  });
}
function hexWithAlpha(hex,opacityPercent){
  const c=hexToRgbSimple(hex);
  const a=Math.max(0,Math.min(100,Number(opacityPercent??100)))/100;
  return `rgba(${c.r},${c.g},${c.b},${a})`;
}
function applyBackground(){
  refreshAutomaticDecorationColors();

  const b=current().background,p=$("paper"),fx=$("paperEffect");
  if(activeBgUrl){URL.revokeObjectURL(activeBgUrl);activeBgUrl=null}
  p.style.backgroundColor=b.solid;p.style.backgroundImage="none";p.style.backgroundSize=b.size;p.style.backgroundPosition="center";p.style.backgroundRepeat="no-repeat";p.style.filter=`brightness(${b.brightness}%)`;
  if(b.mode==="gradient")p.style.backgroundImage=`linear-gradient(${b.angle}deg,${b.grad1},${b.grad2})`;
  if(b.mode==="image"&&b.imageId)getAsset(BG_STORE,b.imageId).then(a=>{if(a?.file){activeBgUrl=URL.createObjectURL(a.file);p.style.backgroundImage=`url("${activeBgUrl}")`}});
  fx.className="paper-effect"+(b.effect!=="none"?" effect-"+b.effect:"");fx.style.opacity=String(b.effectOpacity/100);

  p.style.borderStyle=b.paperBorderStyle||"none";
  p.style.borderColor=hexWithAlpha(b.paperBorderColor||"#d8d2c8",b.paperBorderOpacity??100);
  p.style.borderWidth=(b.paperBorderStyle==="none"?0:(b.paperBorderWidth??1))+"px";
  p.style.boxShadow=`0 ${Math.max(4,(b.paperShadow??16)/2)}px ${Math.max(0,(b.paperShadow??16)*2.8)}px rgba(40,35,30,${Math.min(.28,(b.paperShadow??16)/120)})`;
  p.style.setProperty("--paper-user-frame-inset",((b.paperInnerInset??0)+18)+"px");
  p.style.setProperty("--paper-frame-inset",((b.paperInnerInset??0)+18)+"px");
  p.style.setProperty("--paper-frame-color",hexWithAlpha(b.paperFrameColor||"#bdb5a8",b.paperFrameOpacity??100));
  p.classList.remove("frame-simple","frame-double","frame-corner");
  if(b.paperFrameStyle&&b.paperFrameStyle!=="none")p.classList.add("frame-"+b.paperFrameStyle);

  if(b.mode==="solid") applyAmbientColor(b.solid);
  else if(b.mode==="gradient") applyAmbientColor(averageHex(b.grad1,b.grad2));
  else if(b.ambientColor){
    document.documentElement.style.setProperty("--work",b.ambientColor);
    document.body.style.backgroundColor=b.ambientColor;
    document.querySelector(".workspace").style.backgroundColor=b.ambientColor;
  }

  const _effectRgb=hexToRgbSimple(b.effectColor||"#8f887f");
  document.documentElement.style.setProperty("--paper-effect-rgb",`${_effectRgb.r},${_effectRgb.g},${_effectRgb.b}`);
  renderDecorations();
}
function renderDecorations(){
  const layer=$("symbolLayer");layer.innerHTML="";

  for(const d of currentPage().pageDecorations||[]){
    if(d.type==="text"){
      const el=document.createElement("div");
      el.className=`custom-page-deco text ${d.position}`;
      el.textContent=d.text;
      el.style.fontSize=(d.size||24)+"px";
      layer.appendChild(el);
    }else if(d.type==="image" && d.dataUrl){
      const el=document.createElement("div");
      el.className=`custom-page-deco image ${d.position}`;
      el.style.width=(d.size||80)+"px";
      const img=document.createElement("img");
      img.src=d.dataUrl;
      el.appendChild(img);
      layer.appendChild(el);
    }
  }
}
function findCurrentBlockFromSelection(){
  restoreSelection();
  const sel=getSelection();
  if(!sel?.rangeCount)return null;
  let node=sel.getRangeAt(0).startContainer;
  if(node.nodeType===3)node=node.parentNode;
  while(node && node!==$("editor")){
    if(/^(P|DIV|BLOCKQUOTE|LI|H1|H2|H3)$/.test(node.tagName)) return node;
    node=node.parentNode;
  }
  return null;
}

function makeDividerSpacer(){
  const spacer=document.createElement("div");
  spacer.className="paragraph-divider-spacer";
  spacer.innerHTML="<br>";
  spacer.contentEditable="false";
  return spacer;
}

function insertParagraphDivider(symbol){
  const editorEl=$("editor");
  restoreSelection();
  const sel=getSelection();
  const divider=document.createElement("div");
  divider.className="paragraph-divider";
  divider.dataset.ornament=symbol;
  divider.textContent=symbol;
  divider.contentEditable="false";

  const b=current().background;
  divider.style.fontSize=(b.dividerSize??16)+"px";
  // Blank-line spacers now provide the vertical breathing room.
  divider.style.margin="0";

  const beforeSpacer=makeDividerSpacer();
  const afterSpacer=makeDividerSpacer();
  const nextParagraph=document.createElement("p");
  nextParagraph.innerHTML="<br>";

  const block=findCurrentBlockFromSelection();

  if(block && block.parentNode){
    block.insertAdjacentElement("afterend",beforeSpacer);
    beforeSpacer.insertAdjacentElement("afterend",divider);
    divider.insertAdjacentElement("afterend",afterSpacer);

    let next=afterSpacer.nextElementSibling;
    if(!next || next.classList.contains("paragraph-divider") || next.classList.contains("paragraph-divider-spacer")){
      afterSpacer.insertAdjacentElement("afterend",nextParagraph);
      next=nextParagraph;
    }

    const range=document.createRange();
    range.selectNodeContents(next);
    range.collapse(true);
    sel.removeAllRanges();
    sel.addRange(range);
  }else{
    editorEl.appendChild(beforeSpacer);
    editorEl.appendChild(divider);
    editorEl.appendChild(afterSpacer);
    editorEl.appendChild(nextParagraph);

    const range=document.createRange();
    range.selectNodeContents(nextParagraph);
    range.collapse(true);
    sel.removeAllRanges();
    sel.addRange(range);
  }

  rememberSelection();
  scheduleSave();
}
document.querySelectorAll("[data-symbol]").forEach(b=>{
  b.onclick=()=>insertParagraphDivider(b.dataset.symbol);
});
$("insertCustomDividerBtn").onclick=()=>{
  const text=$("customDividerText").value.trim();
  if(!text)return;
  insertParagraphDivider(text);
};
document.querySelectorAll("[data-deco]").forEach(b=>b.onclick=()=>{const d=b.dataset.deco,arr=current().background.decorations||(current().background.decorations=[]);if(!arr.includes(d))arr.push(d);persist();renderDecorations()});

function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,DBV);q.onupgradeneeded=()=>{const db=q.result;if(!db.objectStoreNames.contains(FONT_STORE))db.createObjectStore(FONT_STORE,{keyPath:"id"});if(!db.objectStoreNames.contains(BG_STORE))db.createObjectStore(BG_STORE,{keyPath:"id"});if(!db.objectStoreNames.contains(SLOT_IMG_STORE))db.createObjectStore(SLOT_IMG_STORE,{keyPath:"id"})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putAsset(store,a){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).put(a);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
async function getAsset(store,id){if(!id)return null;const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(store).objectStore(store).get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
async function getAll(store){const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(store).objectStore(store).getAll();q.onsuccess=()=>res(q.result||[]);q.onerror=()=>rej(q.error)})}
async function delAsset(store,id){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(store,"readwrite");tx.objectStore(store).delete(id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}

$("bgUpload").onchange=async e=>{
  const f=e.target.files?.[0];if(!f)return;
  const id="bg-"+Date.now();
  await putAsset(BG_STORE,{id,file:f,name:f.name});
  current().background.imageId=id;
  current().background.mode="image";
  const avg=await computeImageAverageColor(f);
  current().background.imageAverageColor=avg;
  current().background.ambientColor=ambientFromColor(avg);
  refreshAutomaticDecorationColors();
  persist();syncControls();syncBackgroundOptionPanels();applyBackground();
  e.target.value="";
};
$("fontUpload").onchange=async e=>{
  const f=e.target.files?.[0];if(!f)return;
  const id="font-"+Date.now(),name=f.name.replace(/\.[^.]+$/,"");
  await putAsset(FONT_STORE,{id,file:f,name});
  await loadFonts();
  const family="user-"+id;
  $("fontFamily").value=family;
  if(hasSelection()) applySelectionStyle("fontFamily",family);
  e.target.value="";
};
async function loadFonts(){
  const list=await getAll(FONT_STORE),sel=$("fontFamily");sel.querySelectorAll("[data-custom]").forEach(o=>o.remove());$("customFontList").innerHTML="";
  for(const a of list){const family="user-"+a.id,url=URL.createObjectURL(a.file);try{const face=new FontFace(family,`url(${url})`);await face.load();document.fonts.add(face)}catch{}
    const o=document.createElement("option");o.value=family;o.textContent=a.name;o.dataset.custom="1";sel.appendChild(o);
    const row=document.createElement("div");row.className="asset-row";row.innerHTML=`<span>${esc(a.name)}</span><button>삭제</button>`;row.querySelector("button").onclick=async()=>{await delAsset(FONT_STORE,a.id);await loadFonts()};$("customFontList").appendChild(row)
  }
  const family=effectiveTypography().fontFamily;
  if([...sel.options].some(o=>o.value===family)) sel.value=family;
  applyTypography();
}

function clonePaper(){
  saveCurrent(false);const clone=$("paper").cloneNode(true);clone.removeAttribute("id");clone.querySelectorAll("[id]").forEach(x=>x.removeAttribute("id"));
  const inputs=$("paper").querySelectorAll("input"),ci=clone.querySelectorAll("input");inputs.forEach((x,i)=>{if(ci[i]){ci[i].value=x.value;ci[i].setAttribute("value",x.value);ci[i].readOnly=true}});
  const ed=clone.querySelector(".editor");ed.removeAttribute("contenteditable");ed.style.overflow="visible";ed.style.height="auto";
  return clone
}
let previewPageIndex=0, previewFitScale=1, previewZoom=1;
let saveScope="current";

function applyTypographyToClone(clone,page){
  const t={...defaultTypography(),...current().typography,...(page.pageTypography||{})};
  const ed=clone.querySelector(".editor");
  ed.style.fontFamily=`"${t.fontFamily}"`;
  ed.style.fontSize=(t.fontSizePt??12)+"pt";
  ed.style.letterSpacing=(t.letterSpacing/100)+"em";
  ed.style.lineHeight=String(t.lineHeight??1.45);
  ed.style.color=t.textColor||"#3f3d3b";
  ed.style.fontWeight=t.fontWeight||"400";
  ed.style.fontStyle=t.fontStyle||"normal";
  ed.style.textDecoration=t.textDecoration||"";
  ed.style.textAlign=t.textAlign||"left";
  ed.style.setProperty("--editor-para",(t.paragraphSpacing??0)+"px");
  const scale=(t.widthScale??100)/100;
  ed.style.transform=`scaleX(${scale})`;
  ed.style.transformOrigin="left top";
  ed.style.width=`${100/scale}%`;
}

function clonePageForIndex(pageIndex,{forExport=false}={}){
  const s=current(),page=s.pages[pageIndex];
  const clone=$("paper").cloneNode(true);
  clone.removeAttribute("id");
  clone.querySelectorAll("[id]").forEach(x=>x.removeAttribute("id"));

  const titleInput=clone.querySelector(".title-input");
  const subtitleInput=clone.querySelector(".subtitle-input");

  if(forExport){
    const title=document.createElement("div");
    title.className="export-title";
    title.textContent=page.title||"";
    const subtitle=document.createElement("div");
    subtitle.className="export-subtitle";
    subtitle.textContent=page.subtitle||"";
    titleInput.replaceWith(title);
    subtitleInput.replaceWith(subtitle);
  }else{
    titleInput.value=page.title||"";
    titleInput.setAttribute("value",page.title||"");
    titleInput.readOnly=true;
    subtitleInput.value=page.subtitle||"";
    subtitleInput.setAttribute("value",page.subtitle||"");
    subtitleInput.readOnly=true;

    const liveRect=$("paper").getBoundingClientRect();
    clone.style.setProperty("width",liveRect.width+"px","important");
    clone.style.setProperty("height",liveRect.height+"px","important");
    clone.style.setProperty("min-width",liveRect.width+"px","important");
    clone.style.setProperty("max-width",liveRect.width+"px","important");
    clone.style.setProperty("min-height",liveRect.height+"px","important");
    clone.style.setProperty("max-height",liveRect.height+"px","important");
  }

  clone.style.setProperty("overflow","hidden","important");

  const ed=clone.querySelector(".editor");
  ed.innerHTML=page.content||"";
  ed.removeAttribute("contenteditable");
  ed.style.setProperty("flex","1 1 auto","important");
  ed.style.setProperty("min-height","0","important");
  ed.style.setProperty("height","auto","important");
  ed.style.setProperty("overflow","hidden","important");
  ed.style.setProperty("contain","paint","important");

  applyTypographyToClone(clone,page);

  const footer=clone.querySelector(".paper-footer span");
  if(footer)footer.textContent=[page.pagePrefix,page.pageNumber,page.pageSuffix].filter(Boolean).join(" ");
  return clone;
}

function applyPreviewZoom(){
  const host=$("previewHost"),paper=host.querySelector(".paper");
  if(!paper)return;
  const scale=previewFitScale*previewZoom;
  paper.style.transform=`scale(${scale})`;
  paper.style.transformOrigin="center center";
  $("previewZoomResetBtn").textContent=Math.round(previewZoom*100)+"%";
}
function fitPreviewPage(){
  const host=$("previewHost"),paper=host.querySelector(".paper");
  if(!paper)return;

  paper.style.transform="none";

  // Use more of the available preview area while keeping a small margin.
  const availableW=Math.max(220,host.clientWidth-28);
  const availableH=Math.max(300,host.clientHeight-28);
  const naturalW=parseFloat(paper.style.width)||paper.getBoundingClientRect().width||600;
  const naturalH=parseFloat(paper.style.height)||paper.getBoundingClientRect().height||850;

  previewFitScale=Math.min(availableW/naturalW,availableH/naturalH,1)*0.99;
  applyPreviewZoom();
}
function renderPreviewPage(){
  const s=current();
  previewPageIndex=Math.max(0,Math.min(s.pages.length-1,previewPageIndex));
  const h=$("previewHost");
  h.classList.add("preview-fit-host");
  h.innerHTML="";
  h.appendChild(clonePageForIndex(previewPageIndex));

  $("previewPageLabel").textContent=`${String(previewPageIndex+1).padStart(2,"0")} / ${String(s.pages.length).padStart(2,"0")}`;
  $("previewPrevBtn").disabled=previewPageIndex===0;
  $("previewNextBtn").disabled=previewPageIndex===s.pages.length-1;
  requestAnimationFrame(()=>requestAnimationFrame(fitPreviewPage));
}
$("previewBtn").onclick=()=>{
  saveCurrent(false);
  previewPageIndex=current().currentPageIndex||0;
  previewZoom=1;
  renderPreviewPage();
  $("previewModal").hidden=false;
};
$("previewPrevBtn").onclick=()=>{previewPageIndex--;renderPreviewPage()};
$("previewNextBtn").onclick=()=>{previewPageIndex++;renderPreviewPage()};

$("previewZoomOutBtn").onclick=()=>{
  previewZoom=Math.max(.6,Math.round((previewZoom-.1)*10)/10);
  applyPreviewZoom();
};
$("previewZoomInBtn").onclick=()=>{
  previewZoom=Math.min(1.8,Math.round((previewZoom+.1)*10)/10);
  applyPreviewZoom();
};
$("previewZoomResetBtn").onclick=()=>{
  previewZoom=1;
  applyPreviewZoom();
};


document.querySelectorAll("[data-close-preview]").forEach(x=>x.onclick=()=>{$("previewModal").hidden=true});
$("previewCopyBtn").onclick=async()=>{
  const p=current().pages[previewPageIndex];
  await navigator.clipboard.writeText([p.title,p.subtitle,strip(p.content)].filter(Boolean).join("\n\n"));
};
$("previewSaveBtn").onclick=()=>{$("previewModal").hidden=true;$("saveMenu").classList.add("open")};

async function copyCurrent(){
  saveCurrent(false);
  const p=currentPage(),txt=[p.title,p.subtitle,strip(p.content)].filter(Boolean).join("\n\n");
  await navigator.clipboard.writeText(txt);
}
$("copyBtn").onclick=copyCurrent;
function showSaveStep(step){
  document.querySelectorAll("#saveMenu .save-step").forEach(el=>{
    el.classList.toggle("active",el.dataset.saveStep===step);
  });
}
$("saveMenuBtn").onclick=e=>{
  e.stopPropagation();
  const menu=$("saveMenu");
  const opening=!menu.classList.contains("open");
  menu.classList.toggle("open");
  if(opening){
    saveScope="current";
    showSaveStep("scope");
  }
};

document.querySelectorAll("[data-save-scope]").forEach(btn=>{
  btn.onclick=()=>{
    saveScope=btn.dataset.saveScope;
    $("saveScopeLabel").textContent=saveScope==="current"?"현재 페이지":"전체 페이지";
    showSaveStep("format");
  };
});
$("saveBackBtn").onclick=()=>{
  saveScope="current";
  showSaveStep("scope");
};

document.addEventListener("click",()=>{$("saveMenu").classList.remove("open")});$("saveMenu").onclick=e=>e.stopPropagation();
document.querySelectorAll("[data-export]").forEach(b=>b.onclick=()=>exportFile(b.dataset.export));

async function capture(pageIndex=current().currentPageIndex||0){
  saveCurrent(false);await document.fonts.ready;
  const host=document.createElement("div");host.className="export-host";
  const clone=clonePageForIndex(pageIndex,{forExport:true});host.appendChild(clone);document.body.appendChild(host);
  try{
    await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
    clone.style.setProperty("width","794px","important");
    clone.style.setProperty("height","1123px","important");
    clone.style.setProperty("min-height","1123px","important");
    clone.style.setProperty("max-height","1123px","important");
    clone.querySelector(".editor").style.overflow="hidden";
    return await html2canvas(clone,{
      scale:2,useCORS:true,backgroundColor:null,width:794,height:1123,
      windowWidth:1200,windowHeight:1300,scrollX:0,scrollY:0
    });
  }finally{host.remove()}
}
async function exportFile(type){
  $("saveMenu").classList.remove("open");
  const s=current();
  const currentIndex=s.currentPageIndex||0;

  if(saveScope==="current"){
    const p=s.pages[currentIndex];
    const name=safe(p.title||s.name);

    if(type==="txt"){
      download(
        new Blob(["\ufeff"+[p.title,p.subtitle,strip(p.content)].filter(Boolean).join("\n\n")],{type:"text/plain"}),
        name+".txt"
      );
      return;
    }

    const c=await capture(currentIndex);

    if(type==="png"){
      return c.toBlob(b=>download(b,name+".png"),"image/png");
    }
    if(type==="jpg"){
      return c.toBlob(b=>download(b,name+".jpg"),"image/jpeg",.96);
    }
    if(type==="pdf"){
      const {jsPDF}=window.jspdf;
      const pdf=new jsPDF({unit:"mm",format:"a4",orientation:"portrait"});
      const img=c.toDataURL("image/jpeg",.96);
      pdf.addImage(img,"JPEG",0,0,210,297,undefined,"FAST");
      pdf.save(name+".pdf");
      return;
    }
  }

  // Entire slot/pages
  const baseName=safe(s.name||"document");

  if(type==="txt"){
    const text=s.pages.map((p,i)=>{
      const body=[p.title,p.subtitle,strip(p.content)].filter(Boolean).join("\n\n");
      return `===== PAGE ${String(i+1).padStart(2,"0")} =====\n${body}`;
    }).join("\n\n");
    download(new Blob(["\ufeff"+text],{type:"text/plain"}),baseName+".txt");
    return;
  }

  if(type==="pdf"){
    const {jsPDF}=window.jspdf;
    const pdf=new jsPDF({unit:"mm",format:"a4",orientation:"portrait"});
    for(let i=0;i<s.pages.length;i++){
      const c=await capture(i);
      const img=c.toDataURL("image/jpeg",.96);
      if(i>0)pdf.addPage("a4","portrait");
      pdf.addImage(img,"JPEG",0,0,210,297,undefined,"FAST");
    }
    pdf.save(baseName+".pdf");
    return;
  }

  // Browsers cannot combine multiple independent pages into one PNG/JPG
  // without making a long image, so whole-page image export is stitched vertically.
  if(type==="png" || type==="jpg"){
    const canvases=[];
    for(let i=0;i<s.pages.length;i++){
      canvases.push(await capture(i));
    }

    const width=Math.max(...canvases.map(c=>c.width));
    const gap=24;
    const height=canvases.reduce((sum,c)=>sum+c.height,0)+gap*(canvases.length-1);

    const merged=document.createElement("canvas");
    merged.width=width;
    merged.height=height;
    const ctx=merged.getContext("2d");

    let y=0;
    canvases.forEach(c=>{
      ctx.drawImage(c,0,y);
      y+=c.height+gap;
    });

    const mime=type==="png"?"image/png":"image/jpeg";
    const quality=type==="jpg"?.96:undefined;
    return merged.toBlob(
      b=>download(b,baseName+"-all."+type),
      mime,
      quality
    );
  }
}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}


$("exportBackupBtn").onclick=()=>download(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),"my-editor-backup.json");
$("importBackupInput").onchange=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.slots?.length)throw 0;state=d;currentSlotId=d.currentSlotId||d.slots[0].id;persist();renderAll()}catch{alert("올바른 백업 파일이 아닙니다.")}};r.readAsText(f)};

loadFonts();renderAll();syncBackgroundOptionPanels();

window.addEventListener("resize",()=>{if(!$("previewModal").hidden)fitPreviewPage();});
